APP_DEBUG: false
BIND_LOCAL: false
DATA_PATH: /home/breeze/Develop/MyNoteData
ENCRYPT: true
LOG_LEVEL: NOSET
MAX_BUFFER_SIZE: 536870912
NOTE_DESCRIPTION_LENGTH: 300
PROCESS_NUM: 4
SERVER_HOST: 0.0.0.0
SERVER_PORT: 8008
SERVER_SCHEME: https
USB_MODE: false
FUNCTIONS:
  - rich
  - note
