APP_DEBUG: false
BIND_LOCAL: false
DATA_PATH: /home/breeze/Develop/MyNoteData
DELETE_ORIGINAL_FILE: false
ENCRYPT: true
ITEMS_PER_PAGE: 10
LOG_LEVEL: INFO
MAX_BUFFER_SIZE: 536870912
NOTE_DESCRIPTION_LENGTH: 300
PROCESS_NUM: 1
SERVER_HOST: 0.0.0.0
SERVER_PORT: 8888
SERVER_SCHEME: https
USB_MODE: false
WITH_NGINX: false
FUNCTIONS:
  # - home
  # - search
  - rich
  - note
  # - help
